[package]
name = "adventofcode2018"
version = "0.1.0"
authors = ["Sebastian Nowicki <sebnow@gmail.com>"]

[lib]
bench = false

[dependencies]
aoc-runner = "^0.2.0"
aoc-runner-derive = "^0.2.0"
rayon = "^1.0"
regex = "^1"
failure = "^0.1.3"
lazy_static = "^1.2"
